// Generated by gencpp from file pkg_task1/msgTurtleResult.msg
// DO NOT EDIT!


#ifndef PKG_TASK1_MESSAGE_MSGTURTLERESULT_H
#define PKG_TASK1_MESSAGE_MSGTURTLERESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pkg_task1
{
template <class ContainerAllocator>
struct msgTurtleResult_
{
  typedef msgTurtleResult_<ContainerAllocator> Type;

  msgTurtleResult_()
    : final_x(0)
    , final_y(0)
    , final_theta(0)  {
    }
  msgTurtleResult_(const ContainerAllocator& _alloc)
    : final_x(0)
    , final_y(0)
    , final_theta(0)  {
  (void)_alloc;
    }



   typedef int8_t _final_x_type;
  _final_x_type final_x;

   typedef int8_t _final_y_type;
  _final_y_type final_y;

   typedef int8_t _final_theta_type;
  _final_theta_type final_theta;





  typedef boost::shared_ptr< ::pkg_task1::msgTurtleResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pkg_task1::msgTurtleResult_<ContainerAllocator> const> ConstPtr;

}; // struct msgTurtleResult_

typedef ::pkg_task1::msgTurtleResult_<std::allocator<void> > msgTurtleResult;

typedef boost::shared_ptr< ::pkg_task1::msgTurtleResult > msgTurtleResultPtr;
typedef boost::shared_ptr< ::pkg_task1::msgTurtleResult const> msgTurtleResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pkg_task1::msgTurtleResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pkg_task1::msgTurtleResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pkg_task1::msgTurtleResult_<ContainerAllocator1> & lhs, const ::pkg_task1::msgTurtleResult_<ContainerAllocator2> & rhs)
{
  return lhs.final_x == rhs.final_x &&
    lhs.final_y == rhs.final_y &&
    lhs.final_theta == rhs.final_theta;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pkg_task1::msgTurtleResult_<ContainerAllocator1> & lhs, const ::pkg_task1::msgTurtleResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pkg_task1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pkg_task1::msgTurtleResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pkg_task1::msgTurtleResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_task1::msgTurtleResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_task1::msgTurtleResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_task1::msgTurtleResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_task1::msgTurtleResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pkg_task1::msgTurtleResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dcbe64f721494990ab374cf224b365bf";
  }

  static const char* value(const ::pkg_task1::msgTurtleResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdcbe64f721494990ULL;
  static const uint64_t static_value2 = 0xab374cf224b365bfULL;
};

template<class ContainerAllocator>
struct DataType< ::pkg_task1::msgTurtleResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pkg_task1/msgTurtleResult";
  }

  static const char* value(const ::pkg_task1::msgTurtleResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pkg_task1::msgTurtleResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# result\n"
"int8 final_x\n"
"int8 final_y\n"
"int8 final_theta\n"
;
  }

  static const char* value(const ::pkg_task1::msgTurtleResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pkg_task1::msgTurtleResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.final_x);
      stream.next(m.final_y);
      stream.next(m.final_theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msgTurtleResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pkg_task1::msgTurtleResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pkg_task1::msgTurtleResult_<ContainerAllocator>& v)
  {
    s << indent << "final_x: ";
    Printer<int8_t>::stream(s, indent + "  ", v.final_x);
    s << indent << "final_y: ";
    Printer<int8_t>::stream(s, indent + "  ", v.final_y);
    s << indent << "final_theta: ";
    Printer<int8_t>::stream(s, indent + "  ", v.final_theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PKG_TASK1_MESSAGE_MSGTURTLERESULT_H
