(cl:defpackage gazebo_conveyor-srv
  (:use )
  (:export
   "CONVEYORBELTCONTROL"
   "<CONVEYORBELTCONTROL-REQUEST>"
   "CONVEYORBELTCONTROL-REQUEST"
   "<CONVEYORBELTCONTROL-RESPONSE>"
   "CONVEYORBELTCONTROL-RESPONSE"
  ))

