; Auto-generated. Do not edit!


(cl:in-package pkg_ros_iot_bridge-msg)


;//! \htmlinclude msgRosIotResult.msg.html

(cl:defclass <msgRosIotResult> (roslisp-msg-protocol:ros-message)
  ((flag_success
    :reader flag_success
    :initarg :flag_success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass msgRosIotResult (<msgRosIotResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <msgRosIotResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'msgRosIotResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pkg_ros_iot_bridge-msg:<msgRosIotResult> is deprecated: use pkg_ros_iot_bridge-msg:msgRosIotResult instead.")))

(cl:ensure-generic-function 'flag_success-val :lambda-list '(m))
(cl:defmethod flag_success-val ((m <msgRosIotResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pkg_ros_iot_bridge-msg:flag_success-val is deprecated.  Use pkg_ros_iot_bridge-msg:flag_success instead.")
  (flag_success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <msgRosIotResult>) ostream)
  "Serializes a message object of type '<msgRosIotResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'flag_success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <msgRosIotResult>) istream)
  "Deserializes a message object of type '<msgRosIotResult>"
    (cl:setf (cl:slot-value msg 'flag_success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<msgRosIotResult>)))
  "Returns string type for a message object of type '<msgRosIotResult>"
  "pkg_ros_iot_bridge/msgRosIotResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'msgRosIotResult)))
  "Returns string type for a message object of type 'msgRosIotResult"
  "pkg_ros_iot_bridge/msgRosIotResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<msgRosIotResult>)))
  "Returns md5sum for a message object of type '<msgRosIotResult>"
  "a50265a5223d2c015174ffc1e1099b23")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'msgRosIotResult)))
  "Returns md5sum for a message object of type 'msgRosIotResult"
  "a50265a5223d2c015174ffc1e1099b23")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<msgRosIotResult>)))
  "Returns full string definition for message of type '<msgRosIotResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result~%bool flag_success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'msgRosIotResult)))
  "Returns full string definition for message of type 'msgRosIotResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result~%bool flag_success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <msgRosIotResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <msgRosIotResult>))
  "Converts a ROS message object to a list"
  (cl:list 'msgRosIotResult
    (cl:cons ':flag_success (flag_success msg))
))
