// Generated by gencpp from file pkg_vb_sim/conveyorBeltPowerMsg.msg
// DO NOT EDIT!


#ifndef PKG_VB_SIM_MESSAGE_CONVEYORBELTPOWERMSG_H
#define PKG_VB_SIM_MESSAGE_CONVEYORBELTPOWERMSG_H

#include <ros/service_traits.h>


#include <pkg_vb_sim/conveyorBeltPowerMsgRequest.h>
#include <pkg_vb_sim/conveyorBeltPowerMsgResponse.h>


namespace pkg_vb_sim
{

struct conveyorBeltPowerMsg
{

typedef conveyorBeltPowerMsgRequest Request;
typedef conveyorBeltPowerMsgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct conveyorBeltPowerMsg
} // namespace pkg_vb_sim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pkg_vb_sim::conveyorBeltPowerMsg > {
  static const char* value()
  {
    return "734278aaf6d621cbe98c5cbee4553347";
  }

  static const char* value(const ::pkg_vb_sim::conveyorBeltPowerMsg&) { return value(); }
};

template<>
struct DataType< ::pkg_vb_sim::conveyorBeltPowerMsg > {
  static const char* value()
  {
    return "pkg_vb_sim/conveyorBeltPowerMsg";
  }

  static const char* value(const ::pkg_vb_sim::conveyorBeltPowerMsg&) { return value(); }
};


// service_traits::MD5Sum< ::pkg_vb_sim::conveyorBeltPowerMsgRequest> should match
// service_traits::MD5Sum< ::pkg_vb_sim::conveyorBeltPowerMsg >
template<>
struct MD5Sum< ::pkg_vb_sim::conveyorBeltPowerMsgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pkg_vb_sim::conveyorBeltPowerMsg >::value();
  }
  static const char* value(const ::pkg_vb_sim::conveyorBeltPowerMsgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pkg_vb_sim::conveyorBeltPowerMsgRequest> should match
// service_traits::DataType< ::pkg_vb_sim::conveyorBeltPowerMsg >
template<>
struct DataType< ::pkg_vb_sim::conveyorBeltPowerMsgRequest>
{
  static const char* value()
  {
    return DataType< ::pkg_vb_sim::conveyorBeltPowerMsg >::value();
  }
  static const char* value(const ::pkg_vb_sim::conveyorBeltPowerMsgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pkg_vb_sim::conveyorBeltPowerMsgResponse> should match
// service_traits::MD5Sum< ::pkg_vb_sim::conveyorBeltPowerMsg >
template<>
struct MD5Sum< ::pkg_vb_sim::conveyorBeltPowerMsgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pkg_vb_sim::conveyorBeltPowerMsg >::value();
  }
  static const char* value(const ::pkg_vb_sim::conveyorBeltPowerMsgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pkg_vb_sim::conveyorBeltPowerMsgResponse> should match
// service_traits::DataType< ::pkg_vb_sim::conveyorBeltPowerMsg >
template<>
struct DataType< ::pkg_vb_sim::conveyorBeltPowerMsgResponse>
{
  static const char* value()
  {
    return DataType< ::pkg_vb_sim::conveyorBeltPowerMsg >::value();
  }
  static const char* value(const ::pkg_vb_sim::conveyorBeltPowerMsgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PKG_VB_SIM_MESSAGE_CONVEYORBELTPOWERMSG_H
