// Generated by gencpp from file pkg_vb_sim/ConveyorBeltControlRequest.msg
// DO NOT EDIT!


#ifndef PKG_VB_SIM_MESSAGE_CONVEYORBELTCONTROLREQUEST_H
#define PKG_VB_SIM_MESSAGE_CONVEYORBELTCONTROLREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pkg_vb_sim
{
template <class ContainerAllocator>
struct ConveyorBeltControlRequest_
{
  typedef ConveyorBeltControlRequest_<ContainerAllocator> Type;

  ConveyorBeltControlRequest_()
    : power(0.0)  {
    }
  ConveyorBeltControlRequest_(const ContainerAllocator& _alloc)
    : power(0.0)  {
  (void)_alloc;
    }



   typedef double _power_type;
  _power_type power;





  typedef boost::shared_ptr< ::pkg_vb_sim::ConveyorBeltControlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pkg_vb_sim::ConveyorBeltControlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ConveyorBeltControlRequest_

typedef ::pkg_vb_sim::ConveyorBeltControlRequest_<std::allocator<void> > ConveyorBeltControlRequest;

typedef boost::shared_ptr< ::pkg_vb_sim::ConveyorBeltControlRequest > ConveyorBeltControlRequestPtr;
typedef boost::shared_ptr< ::pkg_vb_sim::ConveyorBeltControlRequest const> ConveyorBeltControlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pkg_vb_sim::ConveyorBeltControlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pkg_vb_sim::ConveyorBeltControlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pkg_vb_sim::ConveyorBeltControlRequest_<ContainerAllocator1> & lhs, const ::pkg_vb_sim::ConveyorBeltControlRequest_<ContainerAllocator2> & rhs)
{
  return lhs.power == rhs.power;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pkg_vb_sim::ConveyorBeltControlRequest_<ContainerAllocator1> & lhs, const ::pkg_vb_sim::ConveyorBeltControlRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pkg_vb_sim

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pkg_vb_sim::ConveyorBeltControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pkg_vb_sim::ConveyorBeltControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_vb_sim::ConveyorBeltControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_vb_sim::ConveyorBeltControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_vb_sim::ConveyorBeltControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_vb_sim::ConveyorBeltControlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pkg_vb_sim::ConveyorBeltControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b61bda1d4e0075084b2082bebb59ea34";
  }

  static const char* value(const ::pkg_vb_sim::ConveyorBeltControlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb61bda1d4e007508ULL;
  static const uint64_t static_value2 = 0x4b2082bebb59ea34ULL;
};

template<class ContainerAllocator>
struct DataType< ::pkg_vb_sim::ConveyorBeltControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pkg_vb_sim/ConveyorBeltControlRequest";
  }

  static const char* value(const ::pkg_vb_sim::ConveyorBeltControlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pkg_vb_sim::ConveyorBeltControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Conveyor belt control\n"
"\n"
"# desired conveyor belt power\n"
"float64 power\n"
"\n"
;
  }

  static const char* value(const ::pkg_vb_sim::ConveyorBeltControlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pkg_vb_sim::ConveyorBeltControlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.power);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConveyorBeltControlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pkg_vb_sim::ConveyorBeltControlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pkg_vb_sim::ConveyorBeltControlRequest_<ContainerAllocator>& v)
  {
    s << indent << "power: ";
    Printer<double>::stream(s, indent + "  ", v.power);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PKG_VB_SIM_MESSAGE_CONVEYORBELTCONTROLREQUEST_H
