// Generated by gencpp from file pkg_vb_sim/conveyorBeltPowerMsgResponse.msg
// DO NOT EDIT!


#ifndef PKG_VB_SIM_MESSAGE_CONVEYORBELTPOWERMSGRESPONSE_H
#define PKG_VB_SIM_MESSAGE_CONVEYORBELTPOWERMSGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pkg_vb_sim
{
template <class ContainerAllocator>
struct conveyorBeltPowerMsgResponse_
{
  typedef conveyorBeltPowerMsgResponse_<ContainerAllocator> Type;

  conveyorBeltPowerMsgResponse_()
    : result(false)  {
    }
  conveyorBeltPowerMsgResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::pkg_vb_sim::conveyorBeltPowerMsgResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pkg_vb_sim::conveyorBeltPowerMsgResponse_<ContainerAllocator> const> ConstPtr;

}; // struct conveyorBeltPowerMsgResponse_

typedef ::pkg_vb_sim::conveyorBeltPowerMsgResponse_<std::allocator<void> > conveyorBeltPowerMsgResponse;

typedef boost::shared_ptr< ::pkg_vb_sim::conveyorBeltPowerMsgResponse > conveyorBeltPowerMsgResponsePtr;
typedef boost::shared_ptr< ::pkg_vb_sim::conveyorBeltPowerMsgResponse const> conveyorBeltPowerMsgResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pkg_vb_sim::conveyorBeltPowerMsgResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pkg_vb_sim::conveyorBeltPowerMsgResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pkg_vb_sim::conveyorBeltPowerMsgResponse_<ContainerAllocator1> & lhs, const ::pkg_vb_sim::conveyorBeltPowerMsgResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pkg_vb_sim::conveyorBeltPowerMsgResponse_<ContainerAllocator1> & lhs, const ::pkg_vb_sim::conveyorBeltPowerMsgResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pkg_vb_sim

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pkg_vb_sim::conveyorBeltPowerMsgResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pkg_vb_sim::conveyorBeltPowerMsgResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_vb_sim::conveyorBeltPowerMsgResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_vb_sim::conveyorBeltPowerMsgResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_vb_sim::conveyorBeltPowerMsgResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_vb_sim::conveyorBeltPowerMsgResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pkg_vb_sim::conveyorBeltPowerMsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::pkg_vb_sim::conveyorBeltPowerMsgResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::pkg_vb_sim::conveyorBeltPowerMsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pkg_vb_sim/conveyorBeltPowerMsgResponse";
  }

  static const char* value(const ::pkg_vb_sim::conveyorBeltPowerMsgResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pkg_vb_sim::conveyorBeltPowerMsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n"
;
  }

  static const char* value(const ::pkg_vb_sim::conveyorBeltPowerMsgResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pkg_vb_sim::conveyorBeltPowerMsgResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct conveyorBeltPowerMsgResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pkg_vb_sim::conveyorBeltPowerMsgResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pkg_vb_sim::conveyorBeltPowerMsgResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PKG_VB_SIM_MESSAGE_CONVEYORBELTPOWERMSGRESPONSE_H
