// Generated by gencpp from file pkg_vb_sim/vacuumGripper.msg
// DO NOT EDIT!


#ifndef PKG_VB_SIM_MESSAGE_VACUUMGRIPPER_H
#define PKG_VB_SIM_MESSAGE_VACUUMGRIPPER_H

#include <ros/service_traits.h>


#include <pkg_vb_sim/vacuumGripperRequest.h>
#include <pkg_vb_sim/vacuumGripperResponse.h>


namespace pkg_vb_sim
{

struct vacuumGripper
{

typedef vacuumGripperRequest Request;
typedef vacuumGripperResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct vacuumGripper
} // namespace pkg_vb_sim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pkg_vb_sim::vacuumGripper > {
  static const char* value()
  {
    return "22dce99b1d1e31fc9ba6b2faee126298";
  }

  static const char* value(const ::pkg_vb_sim::vacuumGripper&) { return value(); }
};

template<>
struct DataType< ::pkg_vb_sim::vacuumGripper > {
  static const char* value()
  {
    return "pkg_vb_sim/vacuumGripper";
  }

  static const char* value(const ::pkg_vb_sim::vacuumGripper&) { return value(); }
};


// service_traits::MD5Sum< ::pkg_vb_sim::vacuumGripperRequest> should match
// service_traits::MD5Sum< ::pkg_vb_sim::vacuumGripper >
template<>
struct MD5Sum< ::pkg_vb_sim::vacuumGripperRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pkg_vb_sim::vacuumGripper >::value();
  }
  static const char* value(const ::pkg_vb_sim::vacuumGripperRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pkg_vb_sim::vacuumGripperRequest> should match
// service_traits::DataType< ::pkg_vb_sim::vacuumGripper >
template<>
struct DataType< ::pkg_vb_sim::vacuumGripperRequest>
{
  static const char* value()
  {
    return DataType< ::pkg_vb_sim::vacuumGripper >::value();
  }
  static const char* value(const ::pkg_vb_sim::vacuumGripperRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pkg_vb_sim::vacuumGripperResponse> should match
// service_traits::MD5Sum< ::pkg_vb_sim::vacuumGripper >
template<>
struct MD5Sum< ::pkg_vb_sim::vacuumGripperResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pkg_vb_sim::vacuumGripper >::value();
  }
  static const char* value(const ::pkg_vb_sim::vacuumGripperResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pkg_vb_sim::vacuumGripperResponse> should match
// service_traits::DataType< ::pkg_vb_sim::vacuumGripper >
template<>
struct DataType< ::pkg_vb_sim::vacuumGripperResponse>
{
  static const char* value()
  {
    return DataType< ::pkg_vb_sim::vacuumGripper >::value();
  }
  static const char* value(const ::pkg_vb_sim::vacuumGripperResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PKG_VB_SIM_MESSAGE_VACUUMGRIPPER_H
