; Auto-generated. Do not edit!


(cl:in-package pkg_iot_ros_bridge-msg)


;//! \htmlinclude msgIotRosResult.msg.html

(cl:defclass <msgIotRosResult> (roslisp-msg-protocol:ros-message)
  ((flag_success
    :reader flag_success
    :initarg :flag_success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass msgIotRosResult (<msgIotRosResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <msgIotRosResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'msgIotRosResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pkg_iot_ros_bridge-msg:<msgIotRosResult> is deprecated: use pkg_iot_ros_bridge-msg:msgIotRosResult instead.")))

(cl:ensure-generic-function 'flag_success-val :lambda-list '(m))
(cl:defmethod flag_success-val ((m <msgIotRosResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pkg_iot_ros_bridge-msg:flag_success-val is deprecated.  Use pkg_iot_ros_bridge-msg:flag_success instead.")
  (flag_success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <msgIotRosResult>) ostream)
  "Serializes a message object of type '<msgIotRosResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'flag_success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <msgIotRosResult>) istream)
  "Deserializes a message object of type '<msgIotRosResult>"
    (cl:setf (cl:slot-value msg 'flag_success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<msgIotRosResult>)))
  "Returns string type for a message object of type '<msgIotRosResult>"
  "pkg_iot_ros_bridge/msgIotRosResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'msgIotRosResult)))
  "Returns string type for a message object of type 'msgIotRosResult"
  "pkg_iot_ros_bridge/msgIotRosResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<msgIotRosResult>)))
  "Returns md5sum for a message object of type '<msgIotRosResult>"
  "a50265a5223d2c015174ffc1e1099b23")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'msgIotRosResult)))
  "Returns md5sum for a message object of type 'msgIotRosResult"
  "a50265a5223d2c015174ffc1e1099b23")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<msgIotRosResult>)))
  "Returns full string definition for message of type '<msgIotRosResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result~%bool flag_success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'msgIotRosResult)))
  "Returns full string definition for message of type 'msgIotRosResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result~%bool flag_success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <msgIotRosResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <msgIotRosResult>))
  "Converts a ROS message object to a list"
  (cl:list 'msgIotRosResult
    (cl:cons ':flag_success (flag_success msg))
))
