// Auto-generated. Do not edit!

// (in-package pkg_task1.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class msgTurtleResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.final_x = null;
      this.final_y = null;
      this.final_theta = null;
    }
    else {
      if (initObj.hasOwnProperty('final_x')) {
        this.final_x = initObj.final_x
      }
      else {
        this.final_x = 0;
      }
      if (initObj.hasOwnProperty('final_y')) {
        this.final_y = initObj.final_y
      }
      else {
        this.final_y = 0;
      }
      if (initObj.hasOwnProperty('final_theta')) {
        this.final_theta = initObj.final_theta
      }
      else {
        this.final_theta = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type msgTurtleResult
    // Serialize message field [final_x]
    bufferOffset = _serializer.int8(obj.final_x, buffer, bufferOffset);
    // Serialize message field [final_y]
    bufferOffset = _serializer.int8(obj.final_y, buffer, bufferOffset);
    // Serialize message field [final_theta]
    bufferOffset = _serializer.int8(obj.final_theta, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type msgTurtleResult
    let len;
    let data = new msgTurtleResult(null);
    // Deserialize message field [final_x]
    data.final_x = _deserializer.int8(buffer, bufferOffset);
    // Deserialize message field [final_y]
    data.final_y = _deserializer.int8(buffer, bufferOffset);
    // Deserialize message field [final_theta]
    data.final_theta = _deserializer.int8(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 3;
  }

  static datatype() {
    // Returns string type for a message object
    return 'pkg_task1/msgTurtleResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'dcbe64f721494990ab374cf224b365bf';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # result
    int8 final_x
    int8 final_y
    int8 final_theta
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new msgTurtleResult(null);
    if (msg.final_x !== undefined) {
      resolved.final_x = msg.final_x;
    }
    else {
      resolved.final_x = 0
    }

    if (msg.final_y !== undefined) {
      resolved.final_y = msg.final_y;
    }
    else {
      resolved.final_y = 0
    }

    if (msg.final_theta !== undefined) {
      resolved.final_theta = msg.final_theta;
    }
    else {
      resolved.final_theta = 0
    }

    return resolved;
    }
};

module.exports = msgTurtleResult;
