// Generated by gencpp from file pkg_iot_ros_bridge/msgIotRosFeedback.msg
// DO NOT EDIT!


#ifndef PKG_IOT_ROS_BRIDGE_MESSAGE_MSGIOTROSFEEDBACK_H
#define PKG_IOT_ROS_BRIDGE_MESSAGE_MSGIOTROSFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pkg_iot_ros_bridge
{
template <class ContainerAllocator>
struct msgIotRosFeedback_
{
  typedef msgIotRosFeedback_<ContainerAllocator> Type;

  msgIotRosFeedback_()
    : percentage_complete(0)  {
    }
  msgIotRosFeedback_(const ContainerAllocator& _alloc)
    : percentage_complete(0)  {
  (void)_alloc;
    }



   typedef int8_t _percentage_complete_type;
  _percentage_complete_type percentage_complete;





  typedef boost::shared_ptr< ::pkg_iot_ros_bridge::msgIotRosFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pkg_iot_ros_bridge::msgIotRosFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct msgIotRosFeedback_

typedef ::pkg_iot_ros_bridge::msgIotRosFeedback_<std::allocator<void> > msgIotRosFeedback;

typedef boost::shared_ptr< ::pkg_iot_ros_bridge::msgIotRosFeedback > msgIotRosFeedbackPtr;
typedef boost::shared_ptr< ::pkg_iot_ros_bridge::msgIotRosFeedback const> msgIotRosFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pkg_iot_ros_bridge::msgIotRosFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pkg_iot_ros_bridge::msgIotRosFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pkg_iot_ros_bridge::msgIotRosFeedback_<ContainerAllocator1> & lhs, const ::pkg_iot_ros_bridge::msgIotRosFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.percentage_complete == rhs.percentage_complete;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pkg_iot_ros_bridge::msgIotRosFeedback_<ContainerAllocator1> & lhs, const ::pkg_iot_ros_bridge::msgIotRosFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pkg_iot_ros_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pkg_iot_ros_bridge::msgIotRosFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pkg_iot_ros_bridge::msgIotRosFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_iot_ros_bridge::msgIotRosFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_iot_ros_bridge::msgIotRosFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_iot_ros_bridge::msgIotRosFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_iot_ros_bridge::msgIotRosFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pkg_iot_ros_bridge::msgIotRosFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d5151973e38c593f60bed311537d61df";
  }

  static const char* value(const ::pkg_iot_ros_bridge::msgIotRosFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd5151973e38c593fULL;
  static const uint64_t static_value2 = 0x60bed311537d61dfULL;
};

template<class ContainerAllocator>
struct DataType< ::pkg_iot_ros_bridge::msgIotRosFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pkg_iot_ros_bridge/msgIotRosFeedback";
  }

  static const char* value(const ::pkg_iot_ros_bridge::msgIotRosFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pkg_iot_ros_bridge::msgIotRosFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# feedback\n"
"int8 percentage_complete\n"
"\n"
;
  }

  static const char* value(const ::pkg_iot_ros_bridge::msgIotRosFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pkg_iot_ros_bridge::msgIotRosFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percentage_complete);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msgIotRosFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pkg_iot_ros_bridge::msgIotRosFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pkg_iot_ros_bridge::msgIotRosFeedback_<ContainerAllocator>& v)
  {
    s << indent << "percentage_complete: ";
    Printer<int8_t>::stream(s, indent + "  ", v.percentage_complete);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PKG_IOT_ROS_BRIDGE_MESSAGE_MSGIOTROSFEEDBACK_H
