// Generated by gencpp from file pkg_iot_ros_bridge/msgIotRosResult.msg
// DO NOT EDIT!


#ifndef PKG_IOT_ROS_BRIDGE_MESSAGE_MSGIOTROSRESULT_H
#define PKG_IOT_ROS_BRIDGE_MESSAGE_MSGIOTROSRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pkg_iot_ros_bridge
{
template <class ContainerAllocator>
struct msgIotRosResult_
{
  typedef msgIotRosResult_<ContainerAllocator> Type;

  msgIotRosResult_()
    : flag_success(false)  {
    }
  msgIotRosResult_(const ContainerAllocator& _alloc)
    : flag_success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _flag_success_type;
  _flag_success_type flag_success;





  typedef boost::shared_ptr< ::pkg_iot_ros_bridge::msgIotRosResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pkg_iot_ros_bridge::msgIotRosResult_<ContainerAllocator> const> ConstPtr;

}; // struct msgIotRosResult_

typedef ::pkg_iot_ros_bridge::msgIotRosResult_<std::allocator<void> > msgIotRosResult;

typedef boost::shared_ptr< ::pkg_iot_ros_bridge::msgIotRosResult > msgIotRosResultPtr;
typedef boost::shared_ptr< ::pkg_iot_ros_bridge::msgIotRosResult const> msgIotRosResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pkg_iot_ros_bridge::msgIotRosResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pkg_iot_ros_bridge::msgIotRosResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pkg_iot_ros_bridge::msgIotRosResult_<ContainerAllocator1> & lhs, const ::pkg_iot_ros_bridge::msgIotRosResult_<ContainerAllocator2> & rhs)
{
  return lhs.flag_success == rhs.flag_success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pkg_iot_ros_bridge::msgIotRosResult_<ContainerAllocator1> & lhs, const ::pkg_iot_ros_bridge::msgIotRosResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pkg_iot_ros_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pkg_iot_ros_bridge::msgIotRosResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pkg_iot_ros_bridge::msgIotRosResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_iot_ros_bridge::msgIotRosResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_iot_ros_bridge::msgIotRosResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_iot_ros_bridge::msgIotRosResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_iot_ros_bridge::msgIotRosResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pkg_iot_ros_bridge::msgIotRosResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a50265a5223d2c015174ffc1e1099b23";
  }

  static const char* value(const ::pkg_iot_ros_bridge::msgIotRosResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa50265a5223d2c01ULL;
  static const uint64_t static_value2 = 0x5174ffc1e1099b23ULL;
};

template<class ContainerAllocator>
struct DataType< ::pkg_iot_ros_bridge::msgIotRosResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pkg_iot_ros_bridge/msgIotRosResult";
  }

  static const char* value(const ::pkg_iot_ros_bridge::msgIotRosResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pkg_iot_ros_bridge::msgIotRosResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# result\n"
"bool flag_success\n"
;
  }

  static const char* value(const ::pkg_iot_ros_bridge::msgIotRosResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pkg_iot_ros_bridge::msgIotRosResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.flag_success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msgIotRosResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pkg_iot_ros_bridge::msgIotRosResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pkg_iot_ros_bridge::msgIotRosResult_<ContainerAllocator>& v)
  {
    s << indent << "flag_success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flag_success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PKG_IOT_ROS_BRIDGE_MESSAGE_MSGIOTROSRESULT_H
