// Generated by gencpp from file pkg_iot_ros_bridge/msgIotRosGoal.msg
// DO NOT EDIT!


#ifndef PKG_IOT_ROS_BRIDGE_MESSAGE_MSGIOTROSGOAL_H
#define PKG_IOT_ROS_BRIDGE_MESSAGE_MSGIOTROSGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pkg_iot_ros_bridge
{
template <class ContainerAllocator>
struct msgIotRosGoal_
{
  typedef msgIotRosGoal_<ContainerAllocator> Type;

  msgIotRosGoal_()
    : protocol()
    , mode()
    , topic()
    , message()  {
    }
  msgIotRosGoal_(const ContainerAllocator& _alloc)
    : protocol(_alloc)
    , mode(_alloc)
    , topic(_alloc)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _protocol_type;
  _protocol_type protocol;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mode_type;
  _mode_type mode;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _topic_type;
  _topic_type topic;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::pkg_iot_ros_bridge::msgIotRosGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pkg_iot_ros_bridge::msgIotRosGoal_<ContainerAllocator> const> ConstPtr;

}; // struct msgIotRosGoal_

typedef ::pkg_iot_ros_bridge::msgIotRosGoal_<std::allocator<void> > msgIotRosGoal;

typedef boost::shared_ptr< ::pkg_iot_ros_bridge::msgIotRosGoal > msgIotRosGoalPtr;
typedef boost::shared_ptr< ::pkg_iot_ros_bridge::msgIotRosGoal const> msgIotRosGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pkg_iot_ros_bridge::msgIotRosGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pkg_iot_ros_bridge::msgIotRosGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pkg_iot_ros_bridge::msgIotRosGoal_<ContainerAllocator1> & lhs, const ::pkg_iot_ros_bridge::msgIotRosGoal_<ContainerAllocator2> & rhs)
{
  return lhs.protocol == rhs.protocol &&
    lhs.mode == rhs.mode &&
    lhs.topic == rhs.topic &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pkg_iot_ros_bridge::msgIotRosGoal_<ContainerAllocator1> & lhs, const ::pkg_iot_ros_bridge::msgIotRosGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pkg_iot_ros_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pkg_iot_ros_bridge::msgIotRosGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pkg_iot_ros_bridge::msgIotRosGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_iot_ros_bridge::msgIotRosGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_iot_ros_bridge::msgIotRosGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_iot_ros_bridge::msgIotRosGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_iot_ros_bridge::msgIotRosGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pkg_iot_ros_bridge::msgIotRosGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e9cbc8cd1a46fb612c6675b9cee83b82";
  }

  static const char* value(const ::pkg_iot_ros_bridge::msgIotRosGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe9cbc8cd1a46fb61ULL;
  static const uint64_t static_value2 = 0x2c6675b9cee83b82ULL;
};

template<class ContainerAllocator>
struct DataType< ::pkg_iot_ros_bridge::msgIotRosGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pkg_iot_ros_bridge/msgIotRosGoal";
  }

  static const char* value(const ::pkg_iot_ros_bridge::msgIotRosGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pkg_iot_ros_bridge::msgIotRosGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# goal\n"
"string protocol\n"
"string mode\n"
"string topic\n"
"string message\n"
;
  }

  static const char* value(const ::pkg_iot_ros_bridge::msgIotRosGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pkg_iot_ros_bridge::msgIotRosGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.protocol);
      stream.next(m.mode);
      stream.next(m.topic);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msgIotRosGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pkg_iot_ros_bridge::msgIotRosGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pkg_iot_ros_bridge::msgIotRosGoal_<ContainerAllocator>& v)
  {
    s << indent << "protocol: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.protocol);
    s << indent << "mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mode);
    s << indent << "topic: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.topic);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PKG_IOT_ROS_BRIDGE_MESSAGE_MSGIOTROSGOAL_H
