// Auto-generated. Do not edit!

// (in-package pkg_ros_iot_bridge.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class msgRosIotFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.percentage_complete = null;
    }
    else {
      if (initObj.hasOwnProperty('percentage_complete')) {
        this.percentage_complete = initObj.percentage_complete
      }
      else {
        this.percentage_complete = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type msgRosIotFeedback
    // Serialize message field [percentage_complete]
    bufferOffset = _serializer.int8(obj.percentage_complete, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type msgRosIotFeedback
    let len;
    let data = new msgRosIotFeedback(null);
    // Deserialize message field [percentage_complete]
    data.percentage_complete = _deserializer.int8(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'pkg_ros_iot_bridge/msgRosIotFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'd5151973e38c593f60bed311537d61df';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # feedback
    int8 percentage_complete
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new msgRosIotFeedback(null);
    if (msg.percentage_complete !== undefined) {
      resolved.percentage_complete = msg.percentage_complete;
    }
    else {
      resolved.percentage_complete = 0
    }

    return resolved;
    }
};

module.exports = msgRosIotFeedback;
